#+title: Reflections

* Reflections
** Honors Ambassador
Time Frame: 2022-2024 (*? check dates*)

My time as an Honors Ambassador at Johnson County Community College is something I miss more & more with each passing semester.

As someone aiming for a Bachelor's in Computer-Science, that might be surprising to hear. I was not hired to write software or help maintain a database of some kind. Instead, to put it as simply as possible, I was hired to /help/ people. That may be an oversimplification of the duties of an Honors Ambassador, but when looking back on my experience, it's the truest way to describe it.

While we were expected to pitch and take on organizing events and projects related to Honors, I found the majority of my day-to-day work was spent helping to complete small tasks assigned to us. From guiding lost students to writing scripts to fix a spreadsheets for a faculty member, each of those little moments of just /helping/ people was something I looked forward to each day. Even replying to the emails students sent to the shared honors inbox gave me that joy. I'll say it again: /even the emails!/  

I was planning to be an Honors Ambassador until the day I graduated Johnson County Community College, which I know may be hard to believe. Even with classes getting harder and the long commute from Lawrence, the thought of leaving my position wasn't something I had even considered. I never could've expected that I would become a part-time caretaker to a newborn. 

Due to a variety of circumstances including postpartum medical complications and busy work schedules; me and my parents found ourselves being the (temporary) main caretakers to my sister and her husband's first child. While the responsibility of caring for Praxton wasn't too bad during that first semester, it was clear by the time he was six months old that something had to give. I was juggling 

It's easy to feel helpless in this day and age. With near-daily news of genocide, people being detained and deported to inhumane prisons without due process, it's hard not to. I've heard many times that during times like these that it's important to be active in your community. To /help/ those around you. 

- Honors taught me how much I love to help people
- Honors taught me how much I love using my skills in programming to help people.
- Honors taught me how, 

** President of Developing Diversity
** MPAC Graduation

